name: Arduino CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile all examples
        uses: arduino/compile-sketches@v1
        with:
          matrix:
              fqbn:
                - arduino:avr:uno
                - arduino:avr:mega
                #- arduino:sam:arduino_due_x
                #- esp32:esp32:esp32
                #- rp2040:rp2040:arduino_nano_rp2040_connect
                #- arduino:mbed_rp2040:rpipico
          libraries: |
            - source-path: .
          sketch-paths: |
            examples
