name: Arduino CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile all examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: |
            arduino:avr:uno
            arduino:avr:mega
            arduino:megaavr:nona4809   # Arduino Nano Every
          platforms: |
            - name: arduino:avr
            - name: arduino:megaavr
          libraries: |
            - source-path: .
          sketch-paths: |
            examples
