name: Arduino CI Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:mega
          - arduino:sam:arduino_due_x
          - esp32:esp32:esp32
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Arduino CLI manually
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
          arduino-cli version

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Install cores
        run: |
          arduino-cli core install arduino:avr
          arduino-cli core install arduino:sam
          arduino-cli core install esp32:esp32

      - name: Compile examples for ${{ matrix.fqbn }}
        run: |
          for sketchdir in $(find examples -type d); do
            if ls $sketchdir/*.ino > /dev/null 2>&1; then
              echo "⏳ Building $sketchdir for ${{ matrix.fqbn }}"
              arduino-cli compile --fqbn ${{ matrix.fqbn }} $sketchdir
            fi
          done
