name: Arduino Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:mega
          - arduino:sam:arduino_due_x
          - esp32:esp32:esp32
          - arduino:mbed_rp2040:rpipico

    steps:
      - uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install cores
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli core install arduino:sam
          arduino-cli core install esp32:esp32
          arduino-cli core install arduino:mbed_rp2040

      - name: Compile examples
        run: |
          for sketch in $(find examples -name "*.ino"); do
            echo "Compiling $sketch for ${{ matrix.fqbn }}"
            arduino-cli compile --fqbn ${{ matrix.fqbn }} --library ./src $sketch
          done